name: rights-free-generation-env
channels:
  - defaults
  - conda-forge
dependencies:
  - flake8==4.0.1
  - isort==5.9.3
  - mypy==0.910
  - pip==21.2.4
  - pydocstyle==6.1.1
  - python~=3.8.13
  - pip:
      - numpy==1.24.3
      - ipykernel==6.16.0
      - scikit-learn==1.2.2
      - matplotlib==3.7.1
      - Pillow==9.4.0
      - beautifulsoup4==4.12.2
      - warcio==1.7.4
      - requests==2.30.0
      - pyarrow==7.0.0
      - ujson==5.7.0
      - openpyxl==3.1.2
      - seaborn==0.12.2
      - cchardet==2.1.7
      - img2dataset==1.41.0
      - "dask[distributed]==2023.4.1"
      - dask-jobqueue==0.8.1
      - bokeh==3.1.1
      - graphviz==0.20.1
